name: Build Android AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.6'

    - name: Accept Licenses and Generate Local Config
      run: |
        yes | sdkmanager --licenses || true
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        gradle wrapper --gradle-version 8.6

    - name: Build Android Bundle (AAB)
      run: |
        chmod +x ./gradlew
        ./gradlew bundleRelease --stacktrace

    - name: Generate Keystore & Sign AAB
      run: |
        keytool -genkey -v -keystore release.keystore -alias windowcraft -keyalg RSA -keysize 2048 -validity 10000 -storepass windowcraft123 -keypass windowcraft123 -dname "CN=WindowCraft, OU=Dev, O=WindowCraftPro, L=IN, S=IN, C=IN"
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore release.keystore -storepass windowcraft123 -keypass windowcraft123 app/build/outputs/bundle/release/app-release.aab windowcraft

    - name: Upload Play Store AAB Bundle
      uses: actions/upload-artifact@v4
      with:
        name: WindowCraft-PlayStore-AAB
        path: app/build/outputs/bundle/release/app-release.aab
